### 00. Pytorch Fundamental

resource :- "https://www.learnpytorch.io/"

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to tensor
## creating tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
vector.ndim , vector.shape

(1, torch.Size([2]))

In [ ]:
# Matrix 
matrix = torch.tensor([
                       [2,3],
                       [4,5]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor_x = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])

In [ ]:
tensor_x.ndim, tensor_x.shape

(3, torch.Size([1, 3, 3]))

In [ ]:
tensor_x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(tensor_x[0][0])
print(tensor_x[0][0][0])

tensor([1, 2, 3])
tensor(1)


In [ ]:
# tensor with dimension (3,4,4)
tensor_3_dim = torch.tensor(
                         [
                             [[0.5510, 0.2981, 0.6302, 0.5871],
                              [0.7076, 0.3730, 0.3600, 0.2577],
                              [0.8368, 0.1554, 0.1390, 0.0678],
                              [0.4496, 0.6624, 0.7304, 0.3617]],
                          
                             [[0.5138, 0.8146, 0.6720, 0.9523],
                              [0.3172, 0.8868, 0.3077, 0.8750],
                              [0.9166, 0.4885, 0.3542, 0.1125],
                              [0.7636, 0.1389, 0.2336, 0.5487]],
                          
                             [[0.9991, 0.8615, 0.5954, 0.3122],
                              [0.5402, 0.7750, 0.0260, 0.8256],
                              [0.4685, 0.4842, 0.0369, 0.0310],
                              [0.3952, 0.1188, 0.4497, 0.3211]]
                          
                         ])
print(tensor_3_dim.ndim)
print(tensor_3_dim.shape)

3
torch.Size([3, 4, 4])


In [ ]:
# creating a tensor with size (2,3,4,4)
tensor_4_dim = torch.tensor(
                  [
                    [
                      [[0.3176, 0.8413, 0.6380, 0.5882],
                       [0.1942, 0.0600, 0.8510, 0.6968],
                       [0.1046, 0.7624, 0.7707, 0.4456],
                       [0.9986, 0.8450, 0.1984, 0.9842]],
                   
                      [[0.1682, 0.3234, 0.1744, 0.8580],
                       [0.9982, 0.4751, 0.8617, 0.4240],
                       [0.3586, 0.9378, 0.1438, 0.7737],
                       [0.7280, 0.0280, 0.0675, 0.0323]],
                   
                      [[0.5429, 0.5763, 0.6014, 0.2468],
                       [0.4043, 0.6162, 0.1933, 0.7036],
                       [0.6104, 0.7113, 0.7113, 0.9487],
                       [0.6271, 0.3043, 0.6168, 0.2726]]
                    ],
                   [
                       [[0.8558, 0.5708, 0.8934, 0.9217],
                        [0.4618, 0.0774, 0.1695, 0.4710],
                        [0.4444, 0.1936, 0.2303, 0.1389],
                        [0.3383, 0.9708, 0.1734, 0.7970]],

                       [[0.8814, 0.4841, 0.1803, 0.6093],
                        [0.8032, 0.1359, 0.2181, 0.9806],
                        [0.3835, 0.1232, 0.8821, 0.6789],
                        [0.4415, 0.7638, 0.6754, 0.8531]],

                       [[0.9826, 0.8736, 0.3568, 0.4553],
                        [0.9019, 0.4283, 0.0695, 0.4791],
                        [0.0414, 0.4349, 0.1928, 0.7803],
                        [0.8900, 0.7021, 0.3000, 0.1801]]
                   ]

                  ]
)
print(tensor_4_dim.ndim)
print(tensor_4_dim.shape)

4
torch.Size([2, 3, 4, 4])


### Rendom Tensor

In [ ]:
#create a random tensor with size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3079, 0.3293, 0.3956, 0.0226],
        [0.6882, 0.9291, 0.7498, 0.0114],
        [0.5440, 0.1382, 0.5402, 0.7846]])

In [ ]:
#create a random tensor with size (1,2,2)
random_tensor_3 = torch.rand(3,4,4)
random_tensor_3

tensor([[[0.2254, 0.0121, 0.8815, 0.5916],
         [0.7563, 0.7735, 0.4873, 0.9288],
         [0.5101, 0.0813, 0.2454, 0.4463],
         [0.6220, 0.5075, 0.3323, 0.4116]],

        [[0.9803, 0.7918, 0.2394, 0.0309],
         [0.4904, 0.6390, 0.7543, 0.5942],
         [0.4566, 0.9476, 0.0101, 0.5460],
         [0.8597, 0.3586, 0.9240, 0.1105]],

        [[0.4956, 0.8175, 0.5706, 0.5520],
         [0.2107, 0.3486, 0.7332, 0.3356],
         [0.6390, 0.0862, 0.4091, 0.3939],
         [0.4545, 0.1544, 0.0081, 0.9825]]])

In [ ]:
#create a random tensor with size (1,2,2)
random_tensor_4 = torch.rand(2,3,4,4)
random_tensor_4

tensor([[[[0.6985, 0.8012, 0.1272, 0.2187],
          [0.3475, 0.5750, 0.3307, 0.9225],
          [0.8400, 0.9974, 0.1832, 0.7155],
          [0.1620, 0.7377, 0.1178, 0.3992]],

         [[0.8653, 0.8753, 0.4563, 0.3800],
          [0.9626, 0.8201, 0.6499, 0.3839],
          [0.6006, 0.0851, 0.9958, 0.6395],
          [0.2530, 0.6451, 0.6820, 0.8978]],

         [[0.9659, 0.3161, 0.6481, 0.2360],
          [0.4245, 0.7138, 0.0900, 0.7911],
          [0.3726, 0.9351, 0.4797, 0.4230],
          [0.1879, 0.5729, 0.0047, 0.8499]]],


        [[[0.0642, 0.2935, 0.5244, 0.5684],
          [0.1880, 0.1840, 0.1774, 0.8780],
          [0.4591, 0.3712, 0.2333, 0.0382],
          [0.4623, 0.5676, 0.9751, 0.7634]],

         [[0.0569, 0.6902, 0.9272, 0.5980],
          [0.7128, 0.2016, 0.6151, 0.0504],
          [0.1714, 0.5052, 0.2192, 0.8366],
          [0.1009, 0.8191, 0.2503, 0.7529]],

         [[0.9274, 0.2018, 0.6315, 0.0460],
          [0.9687, 0.1397, 0.0258, 0.0216],
          [0.4823, 0

In [ ]:
#create a random tensor with similar shape to an image tensor
random_tensor_image = torch.rand(size = (224,224,3))  # Height,Width,colour channel(R,G,B)
print(random_tensor_image.shape)
print(random_tensor_image.ndim)

torch.Size([224, 224, 3])
3


###Zeros and Ones

In [ ]:
#create a tensor with all zeros
tensor_zero = torch.zeros(3,4)
tensor_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor with all ones
tensor_ones = torch.ones(3,4)
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
print(tensor_ones.dtype) #pytorch default date type is float32

torch.float32


###Create a Range of Tensor and Tensor_like

In [ ]:
#create a tensor range from one to thousend with step 100
one_to_thousend_range = torch.arange(start=1,end=1000,step = 100)
one_to_thousend_range

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [ ]:
#create a tensor like
tensor_zero_like = torch.zeros_like(one_to_thousend_range)
tensor_zero_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor DataType

**NOTE:** 3 Type of big Error in pytorch Deep Learning we will face:

1.Tensor are not right datatype

2.Tensor are not right device

3.Tensor are not on the right shape

In [ ]:
#Create Float-32 Tensor
float_32_tensor = torch.tensor([1.0,3.3,4.0],
                               dtype= None,  # What datatype is the Tensor(e.g.- float32,float16 and so on..)
                               device= None,# what device is tensor on
                               requires_grad= False # wheather or not to track gradient with this tensor opearation 
                               )
float_32_tensor.dtype

torch.float32

In [ ]:
#Create float-16 tensor
float_16_tensor = torch.tensor([1.0,3.3,4.0],
                               dtype= torch.float16,  # What datatype is the Tensor(e.g.- float32,float16 and so on..)
                               device= None,# what device is tensor on (default cpu)
                               requires_grad= False # wheather or not to track gradient with this tensor opearation 
                               )
float_16_tensor

tensor([1.0000, 3.3008, 4.0000], dtype=torch.float16)

In [ ]:
#create int32 tensor
int_32_tensor = torch.tensor([1,2,3],
                             dtype=torch.int32,
                             device = None)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

###Getting information from tensors

Once we've created tensors, we might want to get some information from them.

1. Tensors not right datatype - to do get datatype from tensor, can use `tensor.dtype`

2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`

3. Tensor not on the right device- to get device from a tensor, can use `tensor.device`

In [ ]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2988, 0.9128, 0.9574, 0.7214],
        [0.8871, 0.2325, 0.8976, 0.4507],
        [0.0025, 0.7885, 0.7025, 0.4141]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}")
print(f"shape of tensor: {some_tensor.shape}") # or we can use some_tensor.size()

tensor([[0.2988, 0.9128, 0.9574, 0.7214],
        [0.8871, 0.2325, 0.8976, 0.4507],
        [0.0025, 0.7885, 0.7025, 0.4141]])
Datatype of tensor: torch.float32
Device tensor is on: cpu
shape of tensor: torch.Size([3, 4])


###Manipulating Tensor(tensor opearations)
Tensor opearation include:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication



In [ ]:
#create a tensor and add 10
tensor= torch.tensor([2,3,4])

print(tensor + 10)

# we can use PyTorch in-built fuction
print(torch.add(tensor,10))

tensor([12, 13, 14])
tensor([12, 13, 14])


In [ ]:
# Multiply tensor by 10
print(tensor*10)

# we can use PyTorch in-built fuction
print(torch.mul(tensor,10))

tensor([20, 30, 40])
tensor([20, 30, 40])


In [ ]:
# Subtraction tensor by 10
print(tensor-10)

# we can use PyTorch in-built fuction
print(torch.sub(tensor,10))

tensor([-8, -7, -6])
tensor([-8, -7, -6])


In [ ]:
# matrix multiplication

tensor1 = torch.tensor([3,4,5])
tensor2 = torch.tensor([7,9,6])
tensor1*tensor2

tensor([21, 36, 30])

###Matrix multiplication (is all you need)

Two main ways of performing multiplication in neural network and deep learning:

1.Element-wise multiplication

2.Matrix Multiplication


In [ ]:
# Element wise matrix multiplication
print(tensor1,"*",tensor2)
print(f"Equals: {tensor1*tensor2}")

tensor([3, 4, 5]) * tensor([7, 9, 6])
Equals: tensor([21, 36, 30])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor1,tensor2)

tensor(87)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor1 @ tensor2

tensor(87)

In [ ]:
# Matrix multiplication using for loop
%%time
value = 0
for i in range(len(tensor1)):
  value +=tensor1[i]*tensor2[i]

print(value)

tensor(87)
CPU times: user 4.19 ms, sys: 189 µs, total: 4.38 ms
Wall time: 3.65 ms


In [ ]:
# Matrix multiplication using Tensor
%%time
torch.matmul(tensor1,tensor2)

CPU times: user 386 µs, sys: 62 µs, total: 448 µs
Wall time: 322 µs


tensor(87)

In [ ]:
random_tensor = torch.rand(3,2)
# Transpose matrix
print(f"Shape of matrix before Transpose :{random_tensor.shape}")
print(f"shape of matrix after Transpose :{random_tensor.T.shape}")

Shape of matrix before Transpose :torch.Size([3, 2])
shape of matrix after Transpose :torch.Size([2, 3])


###Finding the min,max,mean,sum etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(start = 0,end= 10,step=1,dtype =torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.dtype

torch.float32

In [ ]:
#Find the min
print(f"Minimum : {torch.min(x)}")

#Find the max
print(f"Maximum : {torch.max(x)}")

#Find the sum
print(f"Sum : {torch.sum(x)}")

#Find the mean
print(f"Average : {torch.mean(x)}")

Minimum : 0.0
Maximum : 9.0
Sum : 45.0
Average : 4.5


### Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occour
x.argmin()
print(f"list index value : {x.argmin()} | Minimum value : {x[x.argmin()]}")

list index value : 0 | Minimum value : 0.0


In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> return index position of target tensor where the maximum value occour
print(f"list index value : {x.argmax()} | Maximum value : {x[x.argmax()]}")

list index value : 9 | Maximum value : 9.0


### Reshaping,Stacking,Squeezing and Unsqueezing tensors

* Reshaping - reshaping an input tensor to a defined shape

* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* stacking - combin multiple tensor on top of each other (vstack) or side by side(hstack)

* Squeeze - remove all `1` dimensions from a tensor

* Unsqueez - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dimesion permuted(swapped) in a certain way



In [ ]:
import torch
x = torch.arange(0,10,1,dtype= torch.float32)
x.shape

torch.Size([10])

In [ ]:
# Reshape(add extra dimension)
reshape_tensor = x.reshape(1,10)
print(reshape_tensor)
print(f"Reshape:{reshape_tensor.shape}")

#Or we can reshape it 
reshape_2_5 = x.reshape(2,5) # or we can do it (5,2) but we can't it to (3,5) or (4,5) and so on ...
print(reshape_2_5)

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Reshape:torch.Size([1, 10])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])


In [ ]:
# Change the view
z = x.view(1,10)
z,z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [ ]:
# Chanzing z changes x (because a view of a tensor shares the same memory as the original)

z[:,0] = 5
z,x

(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other
x_stack = torch.stack([x,x,x,x],dim = 0)
print(f"For Dim = 0 : {x_stack}")

x_stack = torch.stack([x,x,x,x],dim = 1)
print(f"\nFor Dim = 1 : {x_stack}")

For Dim = 0 : tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

For Dim = 1 : tensor([[5., 5., 5., 5.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Tensor :{reshape_tensor}")
print(f"Before squeeze Tensor shape is :{reshape_tensor.shape}")


#Remove extra dimension from reshape_tensor
x_squeezed = reshape_tensor.squeeze()
print(f"\nSqueeze tensor : {x_squeezed}")
print(f"After sqeez Tensor shape is : {reshape_tensor.squeeze().shape}")

Tensor :tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Before squeeze Tensor shape is :torch.Size([1, 10])

Squeeze tensor : tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
After sqeez Tensor shape is : torch.Size([10])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specified dimension
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

#Add an extra dimension using torch.unsqueez() method
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor :{x_unsqueezed}")
print(f"New tensor Shape : {x_unsqueezed.shape}")

Previous Target: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([10])

New tensor :tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor Shape : torch.Size([1, 10])


In [ ]:
#torch.permute - rearrange the dimension of a target tensor in a specified oreder
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

###Indexing(selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x)
print(x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])


In [ ]:
# Let's index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's Index on the middle bracket(dim =1)
print(x[0][0]) 
#Or we can use 
print(x[0,0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [ ]:
#Let's index on the most inner bracket(last dimension)
print(x[0][0][0])
#Or we can use 
print(x[0,0,0])

tensor(1)
tensor(1)


In [ ]:
#We can also use ":" to select all of a target dimesion
x[0,1,:],

(tensor([4, 5, 6]),)

###Pytorch tensor & Numpy

* convert Numpy to pytorch Tensor -> `torch.torch.from_numpy(ndarray)`

* convert PyTorch tensor to nupy -> `torch.Tensor.numpy()`

**Note:** 

1. pytorch default data type is `float32`

2. numpy default data type is `float64`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
pytorch_tensor = torch.from_numpy(array)
print(array)
print(pytorch_tensor.dtype)

#We can change datatype to float32
pytorch_tensor_float32 = pytorch_tensor.type(torch.float32)
print(pytorch_tensor_float32.dtype)

[1. 2. 3. 4. 5. 6. 7.]
torch.float64
torch.float32


In [ ]:
#Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducbility(trying to take random out of random)

In sort how a neral network learns:

`start with random number -> tensor opearation -> update random numbers to try and make them better representation of the data -> again ->again ->again`

To reduce the randomness in neural network and pytorch comes the concept of a **random seed**

Essentially what the random seed does is flavour the randomness.


In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.4978, 0.3899, 0.2888, 0.7468],
        [0.6545, 0.3408, 0.6520, 0.6648],
        [0.4989, 0.6547, 0.0618, 0.4979]])
tensor([[0.0552, 0.0362, 0.7421, 0.5992],
        [0.1849, 0.2259, 0.6395, 0.5383],
        [0.4188, 0.4999, 0.9935, 0.5495]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensor
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensor and PyTorch object on the GPUs(and making faster computations)**bold text**


In [ ]:
# check for GPU access with PyTorch
import torch
torch.__version__


'1.13.1+cu116'

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

e.g. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of device
torch.cuda.device_count()

1

In [ ]:
# Create a tensor (default on the cpu)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**Note:** If tensor is on GPU can't transform it to NumPy 

To fix the GPU tensor with NumPy issue,we can first set it to the cpu

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])